### PR TITLE
Configuring for pure-python

### PR DESCRIPTION
**Pull request by mgedmin**
Newer template: builds all branches, drops self-dependency on zope.testrunner in tox.ini.

### CODE REVIEW

**Review by jamadden — APPROVED** [review]
LGTM

**Review by cjwatson — APPROVED** [review]
LGTM.  While you're here, I wonder if you could add a note to CHANGES.rst about adding support for Python 3.9?  Your previous CI work had that effect and it's something we'd ordinarily note in the changelog - I only noticed that it wasn't there after it landed.

**Comment by mgedmin** [comment]
It's probably time to release 5.3.0?

**Comment by icemac** [comment]
> It's probably time to release 5.3.0?

I think this is a good idea.

**Pull request merged**
