### PR TITLE
Fix `package init file missing` warning

### LINKED ISSUE #112: `package init file missing` warning when running tox4
tox gets currently rewritten and the release of the new version was announced as May 2021.

I ran the pre-release [on all Zope and Plone repositories](https://jugmac00.github.io/blog/testing-the-tox-4-pre-release-at-scale/) and found a couple of issues.

I get the following warning when I run the tox pre-release for this repository

`package init file 'src/zope/testrunner/tests/testrunner-ex/__init__.py' not found (or not a regular file)`

Having a look at both the project's  `setup.py`

```
    packages=[
        "zope",
        "zope.testrunner",
        "zope.testrunner.tests.testrunner-ex",
    ],
```

and directory, well, the directory gets declared as package but there is no `__init.py__`.

https://docs.python.org/3/distutils/setupscript.html#listing-whole-packages

The * fix*  should be to add the missing `__init__.py` file.

I am still curious why the new tox version uncovers this issue, and it was hidden in tox 3.

### PR DESCRIPTION
**Pull request by jugmac00**
This fixes #112

### CODE REVIEW

**Review by mgedmin — COMMENTED** [review]
I don't like this, for reasons stated in #112 comments.

I think a better fix would be to remove `testrunner-ex` from the packages list in setup.py

**Comment by jugmac00** [comment]
> I don't like this, for reasons stated in #112 comments.
> 
> I think a better fix would be to remove `testrunner-ex` from the packages list in setup.py

That is what I just did.

Thanks for taking your time!

**Comment by mgedmin** [comment]
Wait, we haven't migrated to github actions yet?  Augh.

Basically +1, but I want to see CI pass because I don't understand why testrunner-ex was added in the first place, and I'm afraid of some nebulous regression.

**Comment by jugmac00** [comment]
> Wait, we haven't migrated to github actions yet? Augh.
> 
> Basically +1, but I want to see CI pass because I don't understand why testrunner-ex was added in the first place, and I'm afraid of some nebulous regression.

Oh wow, didn't notice it, but I should have.. I saw that this package lacks Python 3.9 support, which indirectly means @icemac (or anybody else) did not apply the meta config tool yet.

My local `tox` run is green, but right - better get CI support up and running again.

```
  py27: commands succeeded
  py27-subunit: commands succeeded
ERROR:  pypy: InterpreterNotFound: pypy
ERROR:  pypy-subunit: InterpreterNotFound: pypy
  py35: commands succeeded
  py35-subunit: commands succeeded
  py36: commands succeeded
  py36-subunit: commands succeeded
  py37: commands succeeded
  py37-subunit: commands succeeded
  py38: commands succeeded
  py38-subunit: commands succeeded
  coverage: commands succeeded
  docs: commands succeeded
```

I have not used the meta config tool for quite a while, and back then I was not super successful in doing so, and currently I have a huge backlog with other stuff :-(

**Comment by icemac** [comment]
This PR should be merged after #116 is solved.

**Comment by mgedmin** [comment]
#116 was merged.  I've rebased this on git master.

**Review by icemac — APPROVED** [review]
LGTM.

**Comment by icemac** [comment]
Thank you for this PR and for reviewing it. 😀

**Pull request merged**
